#Project root base path
server:
  port: 8800
  servlet:
    context-path: /api
#SpringDoc params
springdoc:
  version: v1.0.0
  swagger-ui:
    path: /docs/swagger.html
    operationsSorter: method
    defaultModelsExpandDepth: -1
  api-docs:
    path: /docs
    version: openapi_3_1
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  #PostgreSQL connection
  datasource:
    url: jdbc:postgresql://localhost:5432/emc_sgcc_db?user=postgres&password=mypgdbpass
  #Server timezone
  jackson:
    time-zone: America/Lima
    locale: es_ES
#Custom params
custom:
  server:
    local:
      url: http://localhost:8800/api
    prod:
      url: https://www.example.com/api