spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_sgcc?serverTimezone=America/Lima&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    dispatch-options-request: true
jwt:
  custom-secret: sgcc_jwt_secret
